# Generated by Django 3.0.4 on 2021-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210328_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
